<?php
if ( ! defined( 'ABSPATH' ) ) exit;

function li_page_settings() {
    $msg = '';
    if ( isset( $_POST['li_settings_nonce'] ) && wp_verify_nonce( $_POST['li_settings_nonce'], 'li_settings_save' ) ) {
        update_option( 'li_admin_email',     sanitize_email( $_POST['li_admin_email'] ?? '' ) );
        update_option( 'li_platform_name',  sanitize_text_field( $_POST['li_platform_name'] ?? '' ) );
        update_option( 'li_default_split',    floatval( $_POST['li_default_split'] ?? 55 ) );
        update_option( 'li_from_name',       sanitize_text_field( $_POST['li_from_name'] ?? '' ) );
        update_option( 'li_from_email',      sanitize_email( $_POST['li_from_email'] ?? '' ) );
        update_option( 'li_reply_to',        sanitize_email( $_POST['li_reply_to'] ?? '' ) );
        update_option( 'li_auto_confirm',   isset( $_POST['li_auto_confirm'] ) ? 1 : 0 );
        update_option( 'li_min_payout',      floatval( $_POST['li_min_payout'] ?? 25 ) );
        update_option( 'li_currency',      strtoupper( sanitize_text_field( $_POST['li_currency'] ?? 'USD' ) ) );
        update_option( 'li_currency_symbol', sanitize_text_field( $_POST['li_currency_symbol'] ?? '$' ) );
        update_option( 'li_service_key',    sanitize_text_field( $_POST['li_service_key'] ?? '' ) );
        update_option( 'li_stripe_sk',      sanitize_text_field( $_POST['li_stripe_sk'] ?? '' ) );
        update_option( 'li_stripe_pk',      sanitize_text_field( $_POST['li_stripe_pk'] ?? '' ) );
        update_option( 'li_stripe_account_id', sanitize_text_field( $_POST['li_stripe_account_id'] ?? '' ) );
        update_option( 'li_stripe_webhook_secret', sanitize_text_field( $_POST['li_stripe_webhook_secret'] ?? '' ) );
        update_option( 'li_shopify_webhook_secret', sanitize_text_field( $_POST['li_shopify_webhook_secret'] ?? '' ) );
        update_option( 'li_shopify_store',  sanitize_text_field( $_POST['li_shopify_store'] ?? '' ) );
        $msg = '<div class="li-msg-ok">Settings saved.</div>';
    }
    ob_start();
    echo $msg;
    echo '<form method="post" action="" style="max-width:680px;">';
    wp_nonce_field( 'li_settings_save', 'li_settings_nonce' );
    echo '<div class="li-card"><div class="li-card-title">Platform</div>';
    echo '<div class="li-row"><div class="li-field"><label class="li-label">Platform name</label>';
    echo '<input class="li-input" type="text" name="li_platform_name" value="' . esc_attr( get_option( 'li_platform_name', 'Larry Impact' ) ) . '" />';
    echo '<div class="li-hint">Used in emails and notifications.</div></div>';
    echo '<div class="li-field"><label class="li-label">Admin notification email</label>';
    echo '<input class="li-input" type="email" name="li_admin_email" value="' . esc_attr( get_option( 'li_admin_email', get_option( 'admin_email' ) ) ) . '" />';
    echo '<div class="li-hint">Where new application alerts get sent.</div></div></div>';
    echo '<div class="li-field" style="max-width:200px;"><label class="li-label">Default rescue share of net profit %</label>';
    echo '<input class="li-input" type="number" name="li_default_split" min="0" max="100" step="0.01" value="' . esc_attr( get_option( 'li_default_split', 55 ) ) . '" />';
    echo '<div class="li-hint">A net percent (e.g. 55 = 55% of profit). New products use this to derive a gross split.</div></div></div>';
    echo '<div class="li-card"><div class="li-card-title">Supabase</div>';
    echo '<div class="li-row"><div class="li-field"><label class="li-label">Service role key (optional)</label>';
    echo '<input class="li-input" type="password" name="li_service_key" value="' . esc_attr( get_option( 'li_service_key', '' ) ) . '" />';
    echo '<div class="li-hint">If Supabase RLS blocks inserts on orders/split_config, paste the service role key here. It is stored server-side and never shown in the browser.</div></div></div></div>';
    echo '<div class="li-card"><div class="li-card-title">Stripe</div>';
    echo '<div class="li-row"><div class="li-field"><label class="li-label">Secret key</label>';
    echo '<input class="li-input" type="password" name="li_stripe_sk" value="' . esc_attr( get_option( 'li_stripe_sk', '' ) ) . '" />';
    echo '<div class="li-hint">Leave blank to use the WooCommerce Stripe settings. Only override if you need a different key for Stripe Connect.</div></div>';
    echo '<div class="li-field"><label class="li-label">Publishable key</label>';
    echo '<input class="li-input" type="text" name="li_stripe_pk" value="' . esc_attr( get_option( 'li_stripe_pk', '' ) ) . '" />';
    echo '<div class="li-hint">Leave blank to use the WooCommerce Stripe settings.</div></div></div>';
    echo '<div class="li-row"><div class="li-field"><label class="li-label">Platform Stripe account ID</label>';
    echo '<input class="li-input" type="text" name="li_stripe_account_id" value="' . esc_attr( get_option( 'li_stripe_account_id', 'acct_1TbPeB4GUlbY9xGE' ) ) . '" />';
    echo '<div class="li-hint">acct_... for the connected platform (Larry Bev, Inc).</div></div></div>';
    echo '<div class="li-row"><div class="li-field"><label class="li-label">Stripe webhook secret</label>';
    echo '<input class="li-input" type="password" name="li_stripe_webhook_secret" value="' . esc_attr( get_option( 'li_stripe_webhook_secret', '' ) ) . '" />';
    echo '<div class="li-hint">Endpoint signing secret from Stripe. Add this URL in Stripe: ' . esc_url( home_url( '/wp-json/larry-impact/v1/stripe-webhook' ) ) . '</div></div></div></div>';
    echo '<div class="li-card"><div class="li-card-title">Shopify</div>';
    echo '<div class="li-row"><div class="li-field"><label class="li-label">Webhook secret</label>';
    echo '<input class="li-input" type="password" name="li_shopify_webhook_secret" value="' . esc_attr( get_option( 'li_shopify_webhook_secret', '' ) ) . '" />';
    echo '<div class="li-hint">HMAC secret used to verify orders/paid webhooks.</div></div>';
    echo '<div class="li-field"><label class="li-label">Store domain</label>';
    echo '<input class="li-input" type="text" name="li_shopify_store" value="' . esc_attr( get_option( 'li_shopify_store', 'larrybev.myshopify.com' ) ) . '" />';
    echo '<div class="li-hint">Used for admin links (e.g. larrybev.myshopify.com).</div></div></div>';
    echo '<div style="background:#f9f7f4;border:1px solid #e8e3db;border-radius:8px;padding:14px 16px;font-size:12px;color:#6b6560;line-height:1.6;">Webhook endpoint: <code>' . esc_url( home_url( '/wp-json/larry-impact/v1/shopify-webhook' ) ) . '</code></div></div>';
    echo '<div class="li-card"><div class="li-card-title">Email</div>';
    echo '<div class="li-row"><div class="li-field"><label class="li-label">From name</label>';
    echo '<input class="li-input" type="text" name="li_from_name" value="' . esc_attr( get_option( 'li_from_name', 'Larry Impact' ) ) . '" /></div>';
    echo '<div class="li-field"><label class="li-label">From email</label>';
    echo '<input class="li-input" type="email" name="li_from_email" value="' . esc_attr( get_option( 'li_from_email', get_option( 'admin_email' ) ) ) . '" /></div></div>';
    echo '<div class="li-field" style="max-width:340px;"><label class="li-label">Reply-to email</label>';
    echo '<input class="li-input" type="email" name="li_reply_to" value="' . esc_attr( get_option( 'li_reply_to', get_option( 'admin_email' ) ) ) . '" /></div>';
    echo '<div class="li-toggle-row" style="max-width:500px;">';
    echo '<div><div style="font-size:13px;color:#3a3530;">Send confirmation email on application submit</div>';
    echo '<div class="li-hint">Applicants receive acknowledgment immediately after submitting.</div></div>';
    echo '<label class="li-toggle"><input type="checkbox" name="li_auto_confirm" ' . checked( get_option( 'li_auto_confirm', 1 ), 1, false ) . ' /><span class="li-slider"></span></label>';
    echo '</div></div>';
    echo '<div class="li-card"><div class="li-card-title">Payouts</div>';
    echo '<div class="li-row"><div class="li-field" style="max-width:200px;"><label class="li-label">Minimum payout threshold</label>';
    echo '<input class="li-input" type="number" name="li_min_payout" min="0" step="0.01" value="' . esc_attr( get_option( 'li_min_payout', 25 ) ) . '" />';
    echo '<div class="li-hint">Minimum amount before a payout is triggered.</div></div>';
    echo '<div class="li-field" style="max-width:120px;"><label class="li-label">Currency code</label>';
    echo '<input class="li-input" type="text" name="li_currency" value="' . esc_attr( get_option( 'li_currency', 'USD' ) ) . '" />';
    echo '<div class="li-hint">ISO code (USD, EUR, etc.)</div></div>';
    echo '<div class="li-field" style="max-width:80px;"><label class="li-label">Symbol</label>';
    echo '<input class="li-input" type="text" name="li_currency_symbol" value="' . esc_attr( get_option( 'li_currency_symbol', '$' ) ) . '" />';
    echo '<div class="li-hint">$</div></div></div>';
    echo '<div style="background:#f9f7f4;border:1px solid #e8e3db;border-radius:8px;padding:14px 16px;font-size:12px;color:#6b6560;line-height:1.6;"><strong>Payout method:</strong> Manual for now. Direct deposit via Stripe Connect will be configured per rescue when they complete their account setup.</div>';
    echo '</div>';
    echo '<button class="li-btn" type="submit">Save settings</button>';
    echo '</form>';
    li_admin_wrap( 'Settings', ob_get_clean() );
}
